language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t maro42/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true maro42/react-test-app npm run test;

after_success:
  # 각각의 이미지 빌드
  - docker build -t maro42/docker-frontend ./frontend # 운영은 Dockerfile이름이 디폴트이므로 위의 테스트처럼 명시 안해줘되 됨.
  - docker build -t maro42/docker-backend ./backend
  - docker build -t maro42/docker-nginx ./nginx

  # 도커 허브에 로그인
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  #빌드된 이미지들을 도커 허브에 push
  - docker push maro42/docker-frontend
  - docker push maro42/docker-backend
  - docker push maro42/docker-nginx
